"use client";

import React, { useState, useEffect } from "react";
import {
  X,
  ShoppingCart,
  Loader2,
  Apple,
  Beef,
  Milk,
  Wheat,
  Fish,
  Egg,
  Carrot,
  ExternalLink,
  RefreshCw
} from "lucide-react";
import { useQuery, useMutation } from "convex/react";
import { api } from "@/convex/_generated/api";
import { Id } from "@/convex/_generated/dataModel";

interface Ingredient {
  name: string;
  quantity?: string;
  unit?: string;
  category: string;
  displayText: string;
}

interface GroceryListPanelProps {
  isOpen: boolean;
  onClose: () => void;
  userId: string;
}

// Food category icons mapping
const categoryIcons: { [key: string]: React.JSX.Element } = {
  produce: <Apple className="w-4 h-4 text-green-600" />,
  meat: <Beef className="w-4 h-4 text-red-600" />,
  dairy: <Milk className="w-4 h-4 text-blue-600" />,
  bakery: <Wheat className="w-4 h-4 text-amber-600" />,
  seafood: <Fish className="w-4 h-4 text-cyan-600" />,
  eggs: <Egg className="w-4 h-4 text-yellow-600" />,
  vegetables: <Carrot className="w-4 h-4 text-orange-600" />,
  pantry: <ShoppingCart className="w-4 h-4 text-gray-600" />,
  other: <ShoppingCart className="w-4 h-4 text-gray-600" />,
};

export function GroceryListPanel({ isOpen, onClose, userId }: GroceryListPanelProps) {
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [instacartUrl, setInstacartUrl] = useState<string | null>(null);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

  // Fetch the latest grocery list from Convex
  const groceryList = useQuery(api.groceries.getLatestGroceryList, { userId });

  // Fetch meal plan to check if we should auto-generate
  const mealPlan = useQuery(api.mealPlan.getMealPlanByUser, { userId });

  // Toggle checked item mutation
  const toggleCheckedMutation = useMutation(api.groceries.toggleCheckedItem);

  // Group ingredients by category
  const categorizedIngredients: { [key: string]: Ingredient[] } =
    groceryList?.consolidatedIngredients.reduce((acc: any, ingredient: any) => {
      const category = ingredient.category || 'other';
      if (!acc[category]) {
        acc[category] = [];
      }
      acc[category].push(ingredient);
      return acc;
    }, {} as { [key: string]: Ingredient[] }) || {};

  // Handle checkbox changes
  const handleItemCheck = async (ingredientName: string) => {
    if (!groceryList) return;

    try {
      await toggleCheckedMutation({
        listId: groceryList._id,
        ingredientName,
      });
    } catch (error) {
      console.error("Failed to toggle item:", error);
    }
  };

  // Generate new grocery list
  const handleGenerateList = async () => {
    setIsGenerating(true);
    setError(null);

    try {
      const response = await fetch("/api/groceries/generate", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ userId }),
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || "Failed to generate grocery list");
      }

      const data = await response.json();

      if (data.instacartUrl) {
        setInstacartUrl(data.instacartUrl);
      }

      console.log(`Generated list with ${data.ingredientCount} ingredients`);
    } catch (err: any) {
      console.error("Error generating grocery list:", err);
      setError(err.message || "Failed to generate grocery list");
    } finally {
      setIsGenerating(false);
    }
  };

  // Handle opening Instacart - auto-generate if needed
  const handleOpenInstacart = async () => {
    try {
      // Check if we already have an Instacart URL
      const existingUrl = instacartUrl || groceryList?.instacartUrl;

      // Check if list is stale (meal plan changed since list was generated)
      const isStale = isGroceryListStale();

      if (existingUrl && !isStale) {
        // List is fresh, reuse existing URL
        console.log('[GROCERY LIST] Using cached Instacart URL (list is fresh)');
        window.open(existingUrl, '_blank');
        return;
      }

      if (isStale) {
        console.log('[GROCERY LIST] Grocery list is stale, regenerating...');
      } else {
        console.log('[GROCERY LIST] No grocery list exists, generating...');
      }

      // Need to generate list first (either stale or missing)
      setIsGenerating(true);
      setError(null);

      const response = await fetch("/api/groceries/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ userId }),
      });

      if (!response.ok) {
        throw new Error("Failed to generate grocery list");
      }

      const data = await response.json();

      if (data.instacartUrl) {
        setInstacartUrl(data.instacartUrl);
        // Open Instacart in new tab
        window.open(data.instacartUrl, '_blank');
      } else {
        throw new Error("No Instacart URL generated");
      }
    } catch (err: any) {
      console.error("Error opening Instacart:", err);
      setError(err.message || "Failed to open Instacart");
    } finally {
      setIsGenerating(false);
    }
  };

  // Update instacart URL when grocery list changes
  useEffect(() => {
    if (groceryList?.instacartUrl) {
      setInstacartUrl(groceryList.instacartUrl);
    }
  }, [groceryList]);

  // Auto-generate grocery list when panel opens if no list exists but meals are present
  useEffect(() => {
    if (isOpen && !hasAutoGenerated && groceryList === null && mealPlan && mealPlan.length > 0) {
      console.log("Auto-generating grocery list on panel open");
      setHasAutoGenerated(true);
      handleGenerateList();
    }
  }, [isOpen, groceryList, mealPlan, hasAutoGenerated]);

  // Reset auto-generation flag when panel closes
  useEffect(() => {
    if (!isOpen) {
      setHasAutoGenerated(false);
    }
  }, [isOpen]);

  const hasIngredients = Object.keys(categorizedIngredients).length > 0;
  const checkedItems = new Set(groceryList?.checkedItems || []);

  // Check if grocery list is stale (meal plan has changed since list was generated)
  const isGroceryListStale = () => {
    if (!groceryList || !mealPlan || mealPlan.length === 0) {
      return false;
    }

    // Extract current recipe IDs from meal plan
    const currentRecipeIds = mealPlan
      .map((entry: any) => entry.userRecipeId)
      .sort();

    // Extract snapshot recipe IDs from grocery list
    const snapshotRecipeIds = [...(groceryList.mealPlanSnapshot || [])].sort();

    // Compare arrays - check length first
    if (currentRecipeIds.length !== snapshotRecipeIds.length) {
      console.log('[GROCERY LIST] Stale detected: length mismatch', {
        current: currentRecipeIds.length,
        snapshot: snapshotRecipeIds.length
      });
      return true;
    }

    // Check if any IDs differ
    const isDifferent = currentRecipeIds.some((id: string, index: number) => id !== snapshotRecipeIds[index]);

    if (isDifferent) {
      console.log('[GROCERY LIST] Stale detected: recipe IDs differ');
    }

    return isDifferent;
  };

  return (
    <>
      {/* Backdrop */}
      {isOpen && (
        <div
          className="fixed inset-0 bg-black/50 z-40 transition-opacity"
          onClick={onClose}
        />
      )}

      {/* Slide-over panel */}
      <div className={`fixed top-0 left-0 h-full w-full max-w-md bg-white dark:bg-gray-900 shadow-xl z-50 transform transition-transform duration-300 ${
        isOpen ? 'translate-x-0' : '-translate-x-full'
      }`}>
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b dark:border-gray-800">
          <div className="flex items-center gap-2">
            <ShoppingCart className="w-6 h-6 text-green-600" />
            <h2 className="text-xl font-bold text-gray-900 dark:text-white">Grocery List</h2>
          </div>
          <button
            onClick={onClose}
            className="p-2 hover:bg-gray-100 dark:hover:bg-gray-800 rounded-lg transition-colors"
          >
            <X className="w-5 h-5 text-gray-600 dark:text-gray-400" />
          </button>
        </div>

        {/* Content */}
        <div className="h-[calc(100vh-140px)] overflow-y-auto">
          <div className="p-6">
            {error && (
              <div className="mb-4 p-3 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg">
                <p className="text-sm text-red-600 dark:text-red-400">{error}</p>
              </div>
            )}

            {isGenerating ? (
              <div className="flex items-center justify-center py-12">
                <div className="text-center">
                  <Loader2 className="w-8 h-8 animate-spin mx-auto text-green-600 mb-2" />
                  <p className="text-sm text-gray-600 dark:text-gray-400">
                    Consolidating ingredients with AI...
                  </p>
                </div>
              </div>
            ) : !hasIngredients ? (
              <div className="text-center py-12">
                <ShoppingCart className="w-16 h-16 mx-auto text-gray-300 dark:text-gray-700 mb-4" />
                <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">
                  No Grocery List Yet
                </h3>
                <p className="text-sm text-gray-600 dark:text-gray-400 mb-6">
                  Generate a grocery list from your meal plan
                </p>
                <button
                  onClick={handleGenerateList}
                  className="px-4 py-2 bg-green-600 hover:bg-green-700 text-white rounded-lg transition-colors"
                >
                  Generate List
                </button>
              </div>
            ) : (
              <div className="space-y-6">
                {/* Categorized ingredients */}
                {Object.entries(categorizedIngredients).map(([category, items]) => (
                  <div key={category}>
                    <div className="flex items-center gap-2 mb-3">
                      {categoryIcons[category] || <ShoppingCart className="w-4 h-4 text-gray-600" />}
                      <h3 className="font-semibold capitalize text-gray-900 dark:text-white">
                        {category}
                      </h3>
                      <span className="ml-auto px-2 py-0.5 bg-gray-100 dark:bg-gray-800 text-gray-600 dark:text-gray-400 rounded-full text-xs">
                        {items.length}
                      </span>
                    </div>
                    <div className="space-y-2">
                      {items.map((ingredient, index) => {
                        const isChecked = checkedItems.has(ingredient.name);
                        return (
                          <div
                            key={`${category}-${index}`}
                            className={`flex items-center gap-3 p-3 bg-gray-50 dark:bg-gray-800 rounded-lg transition-all ${
                              isChecked ? 'opacity-50' : ''
                            }`}
                          >
                            <input
                              type="checkbox"
                              checked={isChecked}
                              onChange={() => handleItemCheck(ingredient.name)}
                              className="w-4 h-4 text-green-600 rounded border-gray-300 focus:ring-green-500"
                            />
                            <div className="flex-1">
                              <span className={`text-sm font-medium text-gray-900 dark:text-white ${
                                isChecked ? 'line-through text-gray-500 dark:text-gray-500' : ''
                              }`}>
                                {ingredient.displayText}
                              </span>
                            </div>
                          </div>
                        );
                      })}
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>

        {/* Footer - Always show if we have a meal plan */}
        {mealPlan && mealPlan.length > 0 && (
          <div className="absolute bottom-0 left-0 right-0 p-4 border-t dark:border-gray-800 bg-white dark:bg-gray-900">
            <button
              className="w-full flex items-center justify-center gap-2 px-4 py-3 bg-green-600 hover:bg-green-700 disabled:bg-gray-400 disabled:cursor-not-allowed text-white rounded-lg transition-colors font-medium"
              onClick={handleOpenInstacart}
              disabled={isGenerating}
            >
              {isGenerating ? (
                <>
                  <RefreshCw className="w-4 h-4 animate-spin" />
                  Generating List...
                </>
              ) : (
                <>
                  <ExternalLink className="w-4 h-4" />
                  Shop on Instacart
                </>
              )}
            </button>
          </div>
        )}
      </div>
    </>
  );
}
